AWSTemplateFormatVersion: '2010-09-09'
Description: "This template will deploy this job."


Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: hongxing-jar-bucket

  